### ISSUE TITLE
Metadata on <input type="number">

### ISSUE THREAD

**Issue by DanAtShenTech** [thetarkus/django-semanticui-forms#12]
It would be very helpful if you would set metadata based upon the field type in models.py (e.g. models.IntegerField would cause step="1" to be added as metadata, models.DecimalField would yield step=".01", PositiveIntegerField would yield min="1").  Thanks for your consideration.

**Comment by thetarkus** [comment]
Does Django do this by default?

**Comment by DanAtShenTech** [comment]
It looks like it does on the DecimalField but not the IntegerField (and probably not the PositiveInteverField either).  Not sure why they wouldn't on the Integer fields if they are on the DecimalField - the small items that I wrote just seem to make sense.

**Comment by thetarkus** [comment]
Django seems to add a `steps="any"` attribute to DecimalFields and that is passed into the wrapper.  Since there is no built-in option provided by the Django team, I wouldn't be too thrilled of adding this in.

I'm sure you've already found a workaround for this.  For anyone else, the solution is to either add a `step` or `min` attribute on the field in the template or add it to the widget in the form class.

```python
# template, form.html
{% render_field form.decimalfield step=".01" min="1" %}

# form class, form.py
decimalfield = forms.DecimalField(
    widget=forms.NumberInput(attrs={"step": ".01", "min": "1"})
)
```

**Comment by DanAtShenTech** [comment]
Thank you.
